# Generated by Django 3.1.7 on 2021-02-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
